// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBaYIwx4MM_PdIz8USuSjio--RFrf2XOc',
    appId: '1:855638882598:web:7ef4233836269b22f829e7',
    messagingSenderId: '855638882598',
    projectId: 'myecommerceapp-a9faf',
    authDomain: 'myecommerceapp-a9faf.firebaseapp.com',
    storageBucket: 'myecommerceapp-a9faf.appspot.com',
    measurementId: 'G-G6SGPKVFTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC74y_loM6nkyX0DFan5ctqSOrAXDGyCR0',
    appId: '1:855638882598:android:8da9cdf02dfef8d2f829e7',
    messagingSenderId: '855638882598',
    projectId: 'myecommerceapp-a9faf',
    storageBucket: 'myecommerceapp-a9faf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdpXYWif3KtGH_anYbbH3sGRIFwK98ZcQ',
    appId: '1:855638882598:ios:e88fafb1ee9057e7f829e7',
    messagingSenderId: '855638882598',
    projectId: 'myecommerceapp-a9faf',
    storageBucket: 'myecommerceapp-a9faf.appspot.com',
    iosClientId: '855638882598-h464cpp3nm5vl4tli1s00ia9mbf45ho5.apps.googleusercontent.com',
    iosBundleId: 'com.example.myEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdpXYWif3KtGH_anYbbH3sGRIFwK98ZcQ',
    appId: '1:855638882598:ios:e88fafb1ee9057e7f829e7',
    messagingSenderId: '855638882598',
    projectId: 'myecommerceapp-a9faf',
    storageBucket: 'myecommerceapp-a9faf.appspot.com',
    iosClientId: '855638882598-h464cpp3nm5vl4tli1s00ia9mbf45ho5.apps.googleusercontent.com',
    iosBundleId: 'com.example.myEcommerceApp',
  );
}
